# Generated by Django 5.1.6 on 2025-02-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Note', '0003_note_created_at_note_priority_note_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
