# Generated by Django 5.1.6 on 2025-02-25 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Note', '0004_alter_note_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='category',
        ),
    ]
