# Generated by Django 5.1.6 on 2025-02-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Note', '0005_remove_note_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='note',
            name='category',
            field=models.CharField(default='Uncategorized', max_length=100),
        ),
    ]
